int shamash = 13;
int one = 12;
int two = 11;
int three = 10;
int four = 9;
int five = 8;
int six = 7;
int seven = 6;
int eight = 5;

void setup() {
  // put your setup code here, to run once:
  pinMode(shamash, OUTPUT);
  pinMode(one, OUTPUT);
  pinMode(two, OUTPUT);
  pinMode(three, OUTPUT);
  pinMode(four, OUTPUT);
  pinMode(five, OUTPUT);
  pinMode(six, OUTPUT);
  pinMode(seven, OUTPUT);
  pinMode(eight, OUTPUT);
}

void loop() {
  // put your main code here, to run repeatedly:
  digitalWrite(shamash, HIGH);
  digitalWrite(one, HIGH);
  delay(1000);
  digitalWrite(shamash, LOW);
  digitalWrite(one, LOW);
  delay(1000);
  digitalWrite(shamash, HIGH);
  digitalWrite(one, HIGH);
  digitalWrite(two, HIGH);
  delay(1000);
  digitalWrite(shamash, LOW);
  digitalWrite(one, LOW);
  digitalWrite(two, LOW);
  delay(1000);
  digitalWrite(shamash, HIGH);
  digitalWrite(one, HIGH);
  digitalWrite(two, HIGH);
  digitalWrite(three, HIGH);
  delay(1000);
  digitalWrite(shamash, LOW);
  digitalWrite(one, LOW);
  digitalWrite(two, LOW);
  digitalWrite(three, LOW);
  delay(1000);
  digitalWrite(shamash, HIGH);
  digitalWrite(one, HIGH);
  digitalWrite(two, HIGH);
  digitalWrite(three, HIGH);
  digitalWrite(four, HIGH);
  delay(1000);
  digitalWrite(shamash, LOW);
  digitalWrite(one, LOW);
  digitalWrite(two, LOW);
  digitalWrite(three, LOW);
  digitalWrite(four, LOW);
  delay(1000);
  digitalWrite(shamash, HIGH);
  digitalWrite(one, HIGH);
  digitalWrite(two, HIGH);
  digitalWrite(three, HIGH);
  digitalWrite(four, HIGH);
  digitalWrite(five, HIGH);
  delay(1000);
  digitalWrite(shamash, LOW);
  digitalWrite(one, LOW);
  digitalWrite(two, LOW);
  digitalWrite(three, LOW);
  digitalWrite(four, LOW);
  digitalWrite(five, LOW);
  delay(1000);
  digitalWrite(shamash, HIGH);
  digitalWrite(one, HIGH);
  digitalWrite(two, HIGH);
  digitalWrite(three, HIGH);
  digitalWrite(four, HIGH);
  digitalWrite(five, HIGH);
  digitalWrite(six, HIGH);
  delay(1000);
  digitalWrite(shamash, LOW);
  digitalWrite(one, LOW);
  digitalWrite(two, LOW);
  digitalWrite(three, LOW);
  digitalWrite(four, LOW);
  digitalWrite(five, LOW);
  digitalWrite(six, LOW);
  delay(1000);
  digitalWrite(shamash, HIGH);
  digitalWrite(one, HIGH);
  digitalWrite(two, HIGH);
  digitalWrite(three, HIGH);
  digitalWrite(four, HIGH);
  digitalWrite(five, HIGH);
  digitalWrite(six, HIGH);
  digitalWrite(seven, HIGH);
  delay(1000);
  digitalWrite(shamash, LOW);
  digitalWrite(one, LOW);
  digitalWrite(two, LOW);
  digitalWrite(three, LOW);
  digitalWrite(four, LOW);
  digitalWrite(five, LOW);
  digitalWrite(six, LOW);
  digitalWrite(seven, LOW);
  delay(1000);
  digitalWrite(shamash, HIGH);
  digitalWrite(one, HIGH);
  digitalWrite(two, HIGH);
  digitalWrite(three, HIGH);
  digitalWrite(four, HIGH);
  digitalWrite(five, HIGH);
  digitalWrite(six, HIGH);
  digitalWrite(seven, HIGH);
  digitalWrite(eight, HIGH);
  delay(1000);
  digitalWrite(shamash, LOW);
  digitalWrite(one, LOW);
  digitalWrite(two, LOW);
  digitalWrite(three, LOW);
  digitalWrite(four, LOW);
  digitalWrite(five, LOW);
  digitalWrite(six, LOW);
  digitalWrite(seven, LOW);
  digitalWrite(eight, LOW);
  delay(1000);
}
